# Generated by Django 5.1 on 2024-08-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='humidity',
            field=models.FloatField(default=56),
        ),
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
